services:
  postgres:
    image: postgres:16
    container_name: feedback_postgres
    environment:
      POSTGRES_DB: feedbackdb
      POSTGRES_USER: feedback
      POSTGRES_PASSWORD: feedback
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: feedback_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pgdata:
